//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.millerdcjr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid ID { get; set; }
        public string Street { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public System.Guid StateID { get; set; }
        public System.Guid CountryID { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
    }
}
