//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.millerdcjr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.Guid Id { get; set; }
        public string ApplicationName { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Source { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
    }
}
